---
- name: Add apt SD test public key
  apt_key:
    data: "{{ lookup('file','securedrop_test.pub') }}"
    state: present

- name: Temporary fix for GH issue 2938
  file:
    state: absent
    path: "/etc/apt/sources.list.d/tor_apt_freedom_press.list"

- name: Switch apt repo URLs to staging.
  replace:
    dest: "/etc/apt/sources.list.d/tor.apt.freedom.press.list"
    replace: "tor-apt-test.freedom.press"
    regexp: '//tor-apt\.freedom\.press'
  ignore_errors: "yes"
  notify: update tor
